name: Package parsers

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5.0.0
    - name: Install neovim for Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install neovim
        echo 'C:\tools\neovim\nvim-win64\bin' | Out-File -FilePath $env:GITHUB_PATH -Append
    - name: Install neovim for Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        mkdir -p /opt/nvim-bin
        curl -Lo /opt/nvim-bin/nvim https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
        chmod u+x /opt/nvim-bin/nvim
        echo "/opt/nvim-bin" >> "$GITHUB_PATH"
    - name: clone nvim-treesitter
      run: |
        git clone --depth 1 --filter blob:none --branch master https://github.com/nvim-treesitter/nvim-treesitter nvim-treesitter
    - name: Compile parsers
      run: nvim -u install_parsers.lua --headless
    - name: compress and upload parsers
      run: |
        tar -I zstd -cf ${{ env.OUTPUT_FILE }} -C out .
        gh release upload latest ${{ env.OUTPUT_FILE }} --clobber
      env:
        OUTPUT_FILE: parsers-${{ runner.arch }}-${{ runner.os }}.tar.zst
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}